name: calvo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  table_calendar: ^3.1.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^20.0.0
  flutter_notification_listener: ^1.3.4  
  http: ^1.1.0
  sqflite: ^2.3.0  
  path: ^1.8.3
  workmanager: ^0.6.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  image_path: "lib/Icon/calvo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/Icon/calvo.png"
